minimumReleaseAgeExclude:
  - browserslist@4.28.5
  - daisyui@5.6.14 || 5.6.17
  - eslint@10.7.0
  - '@tailwindcss/node@4.3.3'
  - '@tailwindcss/oxide-android-arm64@4.3.3'
  - '@tailwindcss/oxide-darwin-arm64@4.3.3'
  - '@tailwindcss/oxide-darwin-x64@4.3.3'
  - '@tailwindcss/oxide-freebsd-x64@4.3.3'
  - '@tailwindcss/oxide-linux-arm-gnueabihf@4.3.3'
  - '@tailwindcss/oxide-linux-arm64-gnu@4.3.3'
  - '@tailwindcss/oxide-linux-arm64-musl@4.3.3'
  - '@tailwindcss/oxide-linux-x64-gnu@4.3.3'
  - '@tailwindcss/oxide-linux-x64-musl@4.3.3'
  - '@tailwindcss/oxide-wasm32-wasi@4.3.3'
  - '@tailwindcss/oxide-win32-arm64-msvc@4.3.3'
  - '@tailwindcss/oxide-win32-x64-msvc@4.3.3'
  - '@tailwindcss/oxide@4.3.3'
  - '@tailwindcss/vite@4.3.3'
  - '@vue/compiler-core@3.5.40'
  - '@vue/compiler-dom@3.5.40'
  - '@vue/compiler-sfc@3.5.40'
  - '@vue/compiler-ssr@3.5.40'
  - '@vue/reactivity@3.5.40'
  - '@vue/runtime-core@3.5.40'
  - '@vue/runtime-dom@3.5.40'
  - '@vue/server-renderer@3.5.40'
  - '@vue/shared@3.5.40'
  - tailwindcss@4.3.3
  - vite@8.1.5 || 8.2.1
  - vue@3.5.40
shellEmulator: true

trustPolicy: no-downgrade

trustPolicyExclude:
  - semver@6.3.1
  - undici@6.22.0
  - undici-types@6.21.0
packages:
  - packages/*
catalogs:
  default:
    '@antfu/eslint-config': ^9.3.0
    '@tailwindcss/vite': ^4.3.3
    '@types/node': ^26.1.2
    '@vitejs/plugin-vue': ^6.0.8
    '@vitest/coverage-v8': ^4.1.10
    '@vue/test-utils': ^2.4.11
    daisyui: ^5.7.16
    eslint: ^10.8.0
    eslint-plugin-vuejs-accessibility: ^2.5.0
    jsdom: ^30.0.1
    shiki: ^4.4.2
    tailwindcss: ^4.3.3
    typescript: ^6.0.3
    vike: ^0.4.260
    vike-vue: ^0.9.13
    vite: ^8.2.1
    vite-plugin-dts: ^5.0.3
    vitest: ^4.1.10
    vue: ^3.5.41
    vue-tsc: ^3.3.9
onlyBuiltDependencies:
  - esbuild
allowBuilds:
  esbuild: true
